#!/bin/bash
FTP_IP=$1
FTP_USERNAME=$2
FTP_USERPASSWORD=$3
FTP_DIR=$4
PROJECT_FOLDER=$5
SAVE_FOLDER_PATH=$6
echo $PROJECT_FOLDER
echo $SAVE_FOLDER_PATH

ftp() {
	
	sudo apt-get install lftp

	lftp -u $FTP_USERNAME,$FTP_USERPASSWORD $FTP_IP <<-EOT
	cd $FTP_DIR
	mirror -c -n --parallel=10 $FTP_DIR $SAVE_FOLDER_PATH
	EOT

}

full_save() {

	ftp

	echo "full save"
	
	LATEST_BACKUP="$PROJECT_FOLDER+backup_wordpress_`date "+%d.%m.%Y_%H.%M.%S"`.tar.gz"
	tar -czpf $LATEST_BACKUP $SAVE_FOLDER_PATH

}

partial_save() {

	ftp

	echo "partial save"

	TEST_BACKUP_FOLDER=$SAVE_FOLDER_PATH+test

	mkdir $TEST_BACKUP_FOLDER

	tar -C $TEST_BACKUP_FOLDER -xzf $LATEST_BACKUP

	ARCHIVE_FOLDER=$(ls "$TEST_BACKUP_FOLDER")

	DIFFERENCE=$(diff "$PROJECT_FOLDER" "$TEST_BACKUP_FOLDER/$ARCHIVE_FOLDER")
	echo $DIFFERENCE

	if [ ! -z "$DIFFERENCE" ] ; then
		full_save
		echo "saved"
	fi

	rm -r $TEST_BACKUP_FOLDER

}

#LANCEMENT DU SCRIPT

show_usage() {

    echo "Utilisation de la commande :"
    echo ""
    echo "        ./sauvegarde-automatique <1> <2> <3> <4> <5>"
    echo ""
	echo "1: IP du serveur ftp"
	echo "2: Nom d'utilisateur du ftp"
	echo "3: Mot de passe du ftp"
    echo "4: Fichier à sauvegarder"
    echo "5: Fichier dans lequel effectuer la sauvegarde"
    echo "Remarque: Il vaut mieux utiliser des chemins relatifs."
	echo ""

}

#LANCEMENT DU SCRIPT

if [ $1 = "-h" ] || [ $1 = "--help" ] ; then

    show_usage

else
	#PRESETS
	
	if [ ! -d $PROJECT_FOLDER ]; then
		echo "Le dossier à sauvegardé spécifié n'existe pas !"
	fi

	if [ -d $SAVE_FOLDER_PATH ]; then
		echo "Fichier de sauvegarde enregistré !"
		echo "Une sauvegarde à été effectuée, vous pouvez maintenant laisser le script tourner en arrière plan pour effectuer les tâches de sauvegardes automatiques."
		full_save
	else

		echo "Le fichier n'existe pas. Voulez-vous le créer ? (o/n)"
		read entry

		if [ $entry = "o" ] || [ $entry = "O" ]; then
			mkdir $SAVE_FOLDER_PATH
			echo "Dossier créé !"
			echo "Une sauvegarde à été effectuée, vous pouvez maintenant laisser le script tourner en arrière plan pour effectuer les tâches de sauvegardes automatiques."
			full_save
		else
			echo "Opération annulée !"
			exit 
		fi

	fi
	
	#WORKLOOP

	while [ true ]
	do
		
		
		
		sleep 21600

		hours=$((hours+6))
		echo "$hours"

		if test hours = 72 ; then

			full_save
			hours=0

		else 
			
			partial_save

		fi

	done

fi
